use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri::Manager;
use tauri_specta::{collect_commands, Builder};

pub mod app;
pub mod assets;
pub mod commands;
pub mod config;
pub mod content;
pub mod data;
pub mod domain;
pub mod error;
pub mod git;
pub mod hugo;
pub mod persistence;
pub mod preview;
pub mod state;
pub mod theme;
pub mod theme_files;
pub mod watcher;

use crate::app::settings::SettingsStore;
use crate::persistence::workspace_store::WorkspaceStore;
use crate::state::AppState;

/// Single source of truth for the command list.
///
/// Keep this in sync as new commands land. Used by both the runtime entry
/// point and the `gen-bindings` helper binary so the typed TS client never
/// drifts from what's actually registered.
pub fn make_specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::app::app_settings_get,
        commands::app::app_settings_resolve_hugo,
        commands::app::app_settings_save,
        commands::assets::asset_delete,
        commands::assets::asset_import,
        commands::assets::asset_list,
        commands::assets::asset_list_assets,
        commands::assets::asset_list_static,
        commands::config::config_get,
        commands::config::config_save,
        commands::content::content_archetypes,
        commands::content::content_create,
        commands::content::content_get,
        commands::content::content_list,
        commands::content::content_save,
        commands::data::data_create,
        commands::data::data_delete,
        commands::data::data_list,
        commands::data::data_read,
        commands::data::data_write,
        commands::git::git_branch_create,
        commands::git::git_branches,
        commands::git::git_checkout,
        commands::git::git_clone,
        commands::git::git_commit,
        commands::git::git_pull,
        commands::git::git_push,
        commands::git::git_stage,
        commands::git::git_stash_pop,
        commands::git::git_stash_save,
        commands::git::git_status,
        commands::git::git_unstage,
        commands::health_check::health_check,
        commands::preview::preview_start,
        commands::preview::preview_status,
        commands::preview::preview_stop,
        commands::site::site_detect,
        commands::theme::theme_get,
        commands::theme::theme_save_params,
        commands::theme_files::theme_file_read,
        commands::theme_files::theme_file_write,
        commands::theme_files::theme_files_list,
        commands::workspace::workspace_active_site_id,
        commands::workspace::workspace_add_site,
        commands::workspace::workspace_clear_active,
        commands::workspace::workspace_list_sites,
        commands::workspace::workspace_remove_site,
        commands::workspace::workspace_rename_site,
        commands::workspace::workspace_set_active,
    ])
}

pub fn export_typescript_bindings(path: &str) -> Result<(), Box<dyn std::error::Error>> {
    make_specta_builder().export(typescript_config(), path)?;
    Ok(())
}

/// Header injected into the generated `bindings.ts` so the strict TS / ESLint
/// rules of the rest of the codebase don't complain about a file we don't
/// hand-write. Keeps the auto-generator self-contained.
fn typescript_config() -> Typescript {
    Typescript::default()
        .header(
            "// @ts-nocheck\n/* eslint-disable */\n// AUTO-GENERATED by tauri-specta — do not edit by hand.\n",
        )
        // u64 file sizes are emitted as TS `number`. JS numbers are safe up
        // to 2^53 — file sizes that big don't show up in Hugo sites.
        .bigint(BigIntExportBehavior::Number)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    if let Err(err) = try_run() {
        eprintln!("Hugo Studio failed to start: {err}");
        std::process::exit(1);
    }
}

fn try_run() -> Result<(), Box<dyn std::error::Error>> {
    let builder = make_specta_builder();

    // In debug builds export the typed bindings to the frontend so the TS
    // client stays in sync as commands evolve. Release builds skip this.
    #[cfg(debug_assertions)]
    builder.export(typescript_config(), "../src/lib/tauri/bindings.ts")?;

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            let app_data_dir = app.path().app_data_dir()?;
            let workspace_store = WorkspaceStore::new(app_data_dir.join("workspace.json"));
            let settings_store = SettingsStore::new(app_data_dir.join("settings.json"));
            app.manage(AppState::new(workspace_store, settings_store));
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())?;

    Ok(())
}
