use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::{collect_commands, Builder};

pub mod commands;
pub mod config;
pub mod content;
pub mod domain;
pub mod error;
pub mod hugo;
pub mod persistence;
pub mod state;
pub mod theme;
pub mod watcher;

use crate::persistence::workspace_store::WorkspaceStore;
use crate::state::AppState;

/// Single source of truth for the command list.
///
/// Keep this in sync as new commands land. Used by both the runtime entry
/// point and the `gen-bindings` helper binary so the typed TS client never
/// drifts from what's actually registered.
pub fn make_specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::config::config_get,
        commands::config::config_save,
        commands::content::content_get,
        commands::content::content_list,
        commands::content::content_save,
        commands::health_check::health_check,
        commands::site::site_detect,
        commands::theme::theme_get,
        commands::theme::theme_save_params,
        commands::workspace::workspace_active_site_id,
        commands::workspace::workspace_add_site,
        commands::workspace::workspace_clear_active,
        commands::workspace::workspace_list_sites,
        commands::workspace::workspace_remove_site,
        commands::workspace::workspace_rename_site,
        commands::workspace::workspace_set_active,
    ])
}

pub fn export_typescript_bindings(path: &str) -> Result<(), Box<dyn std::error::Error>> {
    make_specta_builder().export(typescript_config(), path)?;
    Ok(())
}

/// Header injected into the generated `bindings.ts` so the strict TS / ESLint
/// rules of the rest of the codebase don't complain about a file we don't
/// hand-write. Keeps the auto-generator self-contained.
fn typescript_config() -> Typescript {
    Typescript::default().header(
        "// @ts-nocheck\n/* eslint-disable */\n// AUTO-GENERATED by tauri-specta — do not edit by hand.\n",
    )
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    if let Err(err) = try_run() {
        eprintln!("Hugo Studio failed to start: {err}");
        std::process::exit(1);
    }
}

fn try_run() -> Result<(), Box<dyn std::error::Error>> {
    let builder = make_specta_builder();

    // In debug builds export the typed bindings to the frontend so the TS
    // client stays in sync as commands evolve. Release builds skip this.
    #[cfg(debug_assertions)]
    builder.export(typescript_config(), "../src/lib/tauri/bindings.ts")?;

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            let app_data_dir = app.path().app_data_dir()?;
            let workspace_path = app_data_dir.join("workspace.json");
            let store = WorkspaceStore::new(workspace_path);
            app.manage(AppState::new(store));
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())?;

    Ok(())
}
