// This file is auto-generated by tauri-specta on every debug `cargo` build.
// The placeholder below keeps the frontend type-checkable before the first
// `npm run tauri dev` run; do not edit by hand.

import { invoke } from "@tauri-apps/api/core";

export type HealthStatus = {
  status: string;
  version: string;
};

export const commands = {
  async healthCheck(): Promise<HealthStatus> {
    return await invoke<HealthStatus>("health_check");
  },
};
