// @ts-nocheck
/* eslint-disable */
// AUTO-GENERATED by tauri-specta — do not edit by hand.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthCheck() : Promise<HealthStatus> {
    return await TAURI_INVOKE("health_check");
},
/**
 * Inspect a path and report whether it's a valid Hugo site.
 * Used by the "Add site" flow to give immediate feedback in the picker.
 */
async siteDetect(path: string) : Promise<Result<DetectionInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("site_detect", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceActiveSiteId() : Promise<Result<SiteId | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_active_site_id") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceAddSite(path: string, name: string | null) : Promise<Result<SiteRef, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_add_site", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceClearActive() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_clear_active") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceListSites() : Promise<Result<SiteRef[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_list_sites") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRemoveSite(id: SiteId) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_remove_site", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRenameSite(id: SiteId, name: string) : Promise<Result<SiteRef, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_rename_site", { id, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceSetActive(id: SiteId) : Promise<Result<Site, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_set_active", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * All errors surfaced to the frontend.
 * 
 * Serialized with a `kind` discriminator and a `message` payload so that the
 * TypeScript side can switch on `kind` without parsing free-form strings.
 */
export type AppError = { kind: "not_a_hugo_site"; message: string } | { kind: "site_not_found"; message: string } | { kind: "not_a_directory"; message: string } | { kind: "path_traversal"; message: string } | { kind: "io"; message: string } | { kind: "serde"; message: string } | { kind: "internal"; message: string }
export type DetectionInfo = { kind: HugoConfigKind; 
/**
 * Absolute path to the discovered file (single-file kinds) or to the
 * `config/_default/` directory (DefaultDirectory).
 */
configPath: string }
export type HealthStatus = { status: string; version: string }
/**
 * Which kind of config layout was found in the site root.
 * 
 * Order matches the priority in [`detect`]: hugo.* > config.* > config/_default/.
 */
export type HugoConfigKind = "hugoToml" | "hugoYaml" | "hugoJson" | "configToml" | "configYaml" | "configJson" | "defaultDirectory"
/**
 * Runtime view of an opened site. M1 only fills the structural pieces
 * (id, paths, detection info); config / theme / languages arrive in M2 / M5 / M3.
 */
export type Site = { id: SiteId; name: string; rootPath: string; contentRoot: string; detection: DetectionInfo }
export type SiteId = string
/**
 * Lightweight site descriptor stored in the workspace; the full `Site`
 * (config, theme, languages…) is only built when a site is opened.
 */
export type SiteRef = { id: SiteId; name: string; rootPath: string; lastOpened: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
