// @ts-nocheck
/* eslint-disable */
// AUTO-GENERATED by tauri-specta — do not edit by hand.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async appSettingsGet() : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_settings_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Echo back the path Hugo Studio would actually use right now (resolved
 * override → env var → PATH). Returns `None` when nothing is reachable —
 * the SettingsDialog uses this to render a green/red status hint.
 */
async appSettingsResolveHugo() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_settings_resolve_hugo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appSettingsSave(next: AppSettings) : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_settings_save", { next }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assetDelete(siteId: SiteId, assetId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("asset_delete", { siteId, assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assetImport(siteId: SiteId, source: string, targetContext: AssetContext) : Promise<Result<AssetRef, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("asset_import", { siteId, source, targetContext }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assetList(siteId: SiteId, contentId: string | null) : Promise<Result<AssetRef[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("asset_list", { siteId, contentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assetListAssets(siteId: SiteId) : Promise<Result<AssetRef[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("asset_list_assets", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assetListStatic(siteId: SiteId) : Promise<Result<AssetRef[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("asset_list_static", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configGet(siteId: SiteId) : Promise<Result<LoadedConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_get", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configSave(siteId: SiteId, merged: JsonValue) : Promise<Result<LoadedConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_save", { siteId, merged }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async contentArchetypes(siteId: SiteId) : Promise<Result<Archetype[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("content_archetypes", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async contentCreate(siteId: SiteId, options: CreateOptions) : Promise<Result<CreatedContent, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("content_create", { siteId, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async contentGet(siteId: SiteId, path: string) : Promise<Result<ContentEditPayload, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("content_get", { siteId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async contentList(siteId: SiteId) : Promise<Result<ContentScanResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("content_list", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async contentSave(siteId: SiteId, path: string, frontMatter: JsonValue, body: string) : Promise<Result<ContentEditPayload, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("content_save", { siteId, path, frontMatter, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dataCreate(siteId: SiteId, relPath: string) : Promise<Result<DataFile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("data_create", { siteId, relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dataDelete(siteId: SiteId, relPath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("data_delete", { siteId, relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dataImport(siteId: SiteId, source: string) : Promise<Result<DataFile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("data_import", { siteId, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dataList(siteId: SiteId) : Promise<Result<DataFile[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("data_list", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dataRead(siteId: SiteId, relPath: string) : Promise<Result<DataFileContent, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("data_read", { siteId, relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dataWrite(siteId: SiteId, relPath: string, text: string) : Promise<Result<DataFileContent, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("data_write", { siteId, relPath, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitBranchCreate(siteId: SiteId, name: string, checkoutAfter: boolean) : Promise<Result<GitStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_branch_create", { siteId, name, checkoutAfter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitBranches(siteId: SiteId) : Promise<Result<GitBranch[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_branches", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitCheckout(siteId: SiteId, branch: string) : Promise<Result<GitStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_checkout", { siteId, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitClone(opts: CloneOptions) : Promise<Result<CloneResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_clone", { opts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitCommit(siteId: SiteId, message: string) : Promise<Result<CommitResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_commit", { siteId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPull(siteId: SiteId, strategy: PullStrategy) : Promise<Result<GitStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_pull", { siteId, strategy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPush(siteId: SiteId) : Promise<Result<GitStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStage(siteId: SiteId, paths: string[]) : Promise<Result<GitStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_stage", { siteId, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStashPop(siteId: SiteId) : Promise<Result<GitStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_stash_pop", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStashSave(siteId: SiteId, message: string) : Promise<Result<GitStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_stash_save", { siteId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStatus(siteId: SiteId) : Promise<Result<GitStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_status", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitUnstage(siteId: SiteId, paths: string[]) : Promise<Result<GitStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_unstage", { siteId, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async healthCheck() : Promise<HealthStatus> {
    return await TAURI_INVOKE("health_check");
},
async previewStart(siteId: SiteId) : Promise<Result<PreviewHandle, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_start", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewStatus() : Promise<Result<PreviewStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewStop() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Inspect a path and report whether it's a valid Hugo site.
 * Used by the "Add site" flow to give immediate feedback in the picker.
 */
async siteDetect(path: string) : Promise<Result<DetectionInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("site_detect", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async themeGet(siteId: SiteId) : Promise<Result<ThemeInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("theme_get", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async themeSaveParams(siteId: SiteId, params: JsonValue) : Promise<Result<ThemeInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("theme_save_params", { siteId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async themeFileRead(siteId: SiteId, relPath: string) : Promise<Result<ThemeFileContent, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("theme_file_read", { siteId, relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async themeFileWrite(siteId: SiteId, relPath: string, text: string) : Promise<Result<ThemeFileContent, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("theme_file_write", { siteId, relPath, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async themeFilesList(siteId: SiteId) : Promise<Result<ThemeFilesIndex, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("theme_files_list", { siteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceActiveSiteId() : Promise<Result<SiteId | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_active_site_id") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceAddSite(path: string, name: string | null) : Promise<Result<SiteRef, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_add_site", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceClearActive() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_clear_active") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceListSites() : Promise<Result<SiteRef[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_list_sites") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRemoveSite(id: SiteId) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_remove_site", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRenameSite(id: SiteId, name: string) : Promise<Result<SiteRef, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_rename_site", { id, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceSetActive(id: SiteId) : Promise<Result<Site, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_set_active", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * All errors surfaced to the frontend.
 * 
 * Serialized with a `kind` discriminator and a `message` payload so that the
 * TypeScript side can switch on `kind` without parsing free-form strings.
 */
export type AppError = { kind: "not_a_hugo_site"; message: string } | { kind: "site_not_found"; message: string } | { kind: "not_a_directory"; message: string } | { kind: "path_traversal"; message: string } | { kind: "io"; message: string } | { kind: "serde"; message: string } | { kind: "internal"; message: string } | { kind: "hugo_binary"; message: string } | { kind: "preview_already_running"; message: string } | { kind: "no_preview_running" }
export type AppSettings = { 
/**
 * Absolute path to a Hugo binary the user wants the preview to use
 * instead of the one on PATH. `None` falls back to
 * `HUGO_STUDIO_HUGO_PATH` env var → PATH lookup (see
 * `preview::locate_hugo`).
 */
hugoPath: string | null }
export type Archetype = { 
/**
 * User-facing name = stem of the archetype file or directory.
 * "default" is reserved for the fallback applied to every section.
 */
name: string; 
/**
 * Absolute path to the archetype's index file (for bundles) or to
 * the archetype file itself (for single pages).
 */
path: string; kind: ContentKind }
export type AssetContext = 
/**
 * Co-locate the file inside the bundle directory of `content_id`.
 * `content_id` is the absolute path to the bundle's index file
 * (matches `ContentSummary.path` for a Branch / Leaf bundle).
 */
{ kind: "bundle"; contentId: string } | 
/**
 * `<site>/static/<subpath>`. Empty subpath = static root.
 */
{ kind: "static"; subpath: string } | 
/**
 * `<site>/assets/<subpath>`. Empty subpath = assets root.
 */
{ kind: "assets"; subpath: string }
/**
 * Coarse classification used by the UI to pick an icon and decide
 * whether to show an inline thumbnail.
 */
export type AssetKind = "image" | "script" | "style" | "document" | "other"
export type AssetRef = { 
/**
 * Stable id: site-relative path with forward slashes.
 */
id: string; name: string; 
/**
 * Absolute path on disk.
 */
path: string; 
/**
 * Relative path from the editor's reference point — for a Bundle
 * import that's just the file name (suitable for `![]()` markdown);
 * for Static / Assets it's the path the file would have when Hugo
 * renders the page (`/<subpath>/<name>` for static).
 */
relativeLink: string; kind: AssetKind; size: number; 
/**
 * Friendly label for the UI ("posts/hello/", "static/img/", …).
 */
contextLabel: string }
/**
 * Language of the body — drives the editor mode and whether the Rich
 * (Milkdown) tab applies. Inferred from the file extension by
 * [`body_format_for_path`]; nothing in the on-disk format determines
 * it directly.
 */
export type BodyFormat = "markdown" | "html"
export type CloneOptions = { url: string; 
/**
 * Absolute path of the destination directory. Must NOT exist yet.
 */
dest: string; 
/**
 * Optional branch to check out after clone.
 */
branch: string | null }
export type CloneResult = { dest: string; head: string | null }
export type CommitResult = { oid: string; summary: string }
export type ConfigFormat = "toml" | "yaml" | "json"
/**
 * One config source on disk plus its current parsed contents.
 */
export type ConfigSource = { path: string; format: ConfigFormat; 
/**
 * Top-level key under which this file's contents are merged. `null`
 * means the file's keys live at the merged root (the canonical
 * `hugo.{toml,yaml,json}` case).
 */
mountKey: string | null }
export type ContentEditPayload = { format: FrontMatterFormat; 
/**
 * Body language — drives editor mode and whether the WYSIWYG tab
 * is offered. Inferred from extension, not from on-disk bytes.
 */
bodyFormat: BodyFormat; frontMatter: JsonValue; body: string; schema: FrontMatterSchema; 
/**
 * Absolute path of the file the editor is acting on. Surfaced so the
 * UI can show a "reveal in finder" affordance later.
 */
path: string }
/**
 * Hugo's three structural content kinds, plus the synthetic `Section`
 * for directories that contain content but no `_index.*`.
 */
export type ContentKind = "section" | "branchBundle" | "leafBundle" | "singlePage"
export type ContentScanResult = { languageInfo: LanguageInfo; items: ContentSummary[] }
export type ContentSummary = { 
/**
 * Stable ID = path relative to the language-resolved content root,
 * using forward slashes. Distinct translations of the same logical
 * page share the same `id` but have different `language`.
 */
id: string; kind: ContentKind; 
/**
 * Top-level section under content/ (e.g. "posts", "docs"). `None`
 * for items that sit at the very top (`_index.md` of the site).
 */
section: string | null; language: string; 
/**
 * Absolute filesystem path to the file the user would edit.
 * For bundles this is the index file; for sections it's the
 * directory itself (no editable target until M4 introduces virtual
 * section editing).
 */
path: string; title: string | null; draft: boolean; date: string | null; depth: number }
export type CreateOptions = { section: string; slug: string; 
/**
 * Optional explicit archetype name (matches `Archetype.name`); when
 * `None` the resolver walks `<section>` → `default` → built-in.
 */
archetype: string | null; 
/**
 * Optional language code. When the site uses the directory
 * strategy, this determines the `<lang>/` prefix; for the filename
 * strategy it becomes a `.lang` suffix on the file stem.
 */
language: string | null }
export type CreatedContent = { 
/**
 * Absolute path of the created file (or its index, for bundles).
 */
path: string; 
/**
 * Site-relative content id (`posts/hello.md` or `posts/hello/`).
 */
id: string; kind: ContentKind; language: string | null; archetypeUsed: string }
export type DataFile = { 
/**
 * Stable id: site-relative path with forward slashes.
 */
id: string; 
/**
 * File name including extension.
 */
name: string; 
/**
 * Path under `data/` (forward slashes), without the `data/`
 * prefix — useful for grouping in the UI sidebar.
 */
relPath: string; 
/**
 * Absolute path on disk.
 */
path: string; format: DataFormat; size: number }
export type DataFileContent = { format: DataFormat; 
/**
 * Raw UTF-8 contents — the frontend parses CSV / JSON itself so
 * the editor stays in charge of representation (and so we don't
 * have to round-trip a structured form back through serde).
 */
text: string }
/**
 * Coarse classification of a data file based on extension. The
 * frontend uses this to choose the editor (grid vs source).
 */
export type DataFormat = "csv" | "json" | "yaml" | "toml" | "other"
export type DetectionInfo = { kind: HugoConfigKind; 
/**
 * Absolute path to the discovered file (single-file kinds) or to the
 * `config/_default/` directory (DefaultDirectory).
 */
configPath: string }
export type FieldDef = { key: string; label: string; fieldType: FieldType; required: boolean; default: JsonValue | null; enumValues: string[] | null; group: string | null; hidden: boolean; description: string | null }
export type FieldType = "string" | "text" | "number" | "boolean" | "date" | "dateTime" | 
/**
 * `Array<String>` rendered as a chip-style input. Combined with
 * `enum_values` for autocomplete.
 */
"tags" | 
/**
 * `Array<String>` without autocomplete (e.g. `aliases`).
 */
"stringArray" | 
/**
 * Catch-all for nested objects, arrays of objects, mixed-type
 * arrays, and unknown shapes — edited as raw JSON.
 */
"json"
export type FrontMatterFormat = "toml" | "yaml" | "json"
export type FrontMatterSchema = { fields: FieldDef[]; unknownFieldsPolicy: UnknownFieldsPolicy }
export type GitBranch = { name: string; isCurrent: boolean; 
/**
 * Tracking branch (e.g. `origin/main`) when configured.
 */
upstream: string | null }
export type GitChange = { path: string; status: GitChangeStatus; 
/**
 * True when the change is in the index (staged), false when in the
 * working tree only.
 */
staged: boolean }
export type GitChangeStatus = "new" | "modified" | "deleted" | "renamed" | "untracked" | "conflicted" | "ignored" | "typeChange"
export type GitStatus = { 
/**
 * `None` when the repository has no commits yet or is in a detached
 * HEAD state.
 */
branch: string | null; 
/**
 * Resolved upstream branch name like `origin/main`, or `None` when
 * the current branch has no upstream configured.
 */
upstream: string | null; ahead: number; behind: number; changes: GitChange[]; remotes: string[]; 
/**
 * True when the directory is a git repo at all.
 */
isRepo: boolean; 
/**
 * Convenience flag for the UI: anything to commit / push.
 */
clean: boolean }
export type HealthStatus = { status: string; version: string }
/**
 * Which kind of config layout was found in the site root.
 * 
 * Order matches the priority in [`detect`]: hugo.* > config.* > config/_default/.
 */
export type HugoConfigKind = "hugoToml" | "hugoYaml" | "hugoJson" | "configToml" | "configYaml" | "configJson" | "defaultDirectory"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Language = { code: string; name: string; weight: number }
export type LanguageInfo = { strategy: LanguageStrategy; languages: Language[]; defaultLanguage: string }
export type LanguageStrategy = 
/**
 * No `languages` block in config — site is monolingual.
 */
"mono" | 
/**
 * Translations live as `posts/hello.en.md`, `posts/hello.it.md`.
 */
"filename" | 
/**
 * Translations live under `content/<lang>/posts/hello.md`.
 */
"directory"
/**
 * Result of [`load`] — both the canonical merged JSON for the UI to
 * render, and the per-file mapping needed to write changes back.
 */
export type LoadedConfig = { format: ConfigFormat; sources: ConfigSource[]; merged: JsonValue }
export type PreviewHandle = { url: string; port: number; hugoPath: string }
export type PreviewStatus = { running: boolean; url: string | null; port: number | null }
/**
 * How to resolve a non-fast-forward situation when pulling.
 */
export type PullStrategy = 
/**
 * Refuse to pull anything that isn't a clean fast-forward — the
 * safe default. The UI surfaces a button to retry with `ForceReset`
 * after explicit confirmation.
 */
"fastForward" | 
/**
 * `git fetch && git reset --hard <upstream>` — local commits not in
 * the upstream are silently discarded. Combine with [`stash_save`]
 * beforehand if you also want to preserve working-tree changes.
 */
"forceReset"
export type SchemaSource = 
/**
 * Authoritative schema shipped by the theme author at
 * `themes/<name>/.hugoeditor/theme-schema.json`.
 */
"manifest" | 
/**
 * Inferred from the theme's `[params]` defaults (`config.*` /
 * `theme.toml`).
 */
"defaults" | 
/**
 * Last resort — derived from the values currently set in the site's
 * config.
 */
"inferred"
/**
 * Runtime view of an opened site. M1 only fills the structural pieces
 * (id, paths, detection info); config / theme / languages arrive in M2 / M5 / M3.
 */
export type Site = { id: SiteId; name: string; rootPath: string; contentRoot: string; detection: DetectionInfo }
export type SiteId = string
/**
 * Lightweight site descriptor stored in the workspace; the full `Site`
 * (config, theme, languages…) is only built when a site is opened.
 */
export type SiteRef = { id: SiteId; name: string; rootPath: string; lastOpened: string }
export type ThemeFile = { 
/**
 * Path relative to the theme directory, forward slashes. Stable id.
 */
relPath: string; name: string; 
/**
 * Top-level subdirectory the file lives under (`layouts`, `assets`,
 * …). Empty string for files at the theme root.
 */
category: string; 
/**
 * Absolute path on disk.
 */
path: string; format: ThemeFileFormat; size: number }
export type ThemeFileContent = { format: ThemeFileFormat; text: string }
/**
 * Coarse classification of a theme file based on extension. The
 * frontend uses this to choose the editor's language extension.
 */
export type ThemeFileFormat = "html" | "css" | "scss" | "js" | "ts" | "json" | "yaml" | "toml" | "markdown" | "other"
export type ThemeFilesIndex = { themeName: string | null; themePath: string | null; files: ThemeFile[] }
export type ThemeInfo = { themeName: string | null; themePath: string | null; schema: FrontMatterSchema; source: SchemaSource; params: JsonValue }
export type UnknownFieldsPolicy = "preserve" | "warn" | "strip"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
